# -*- coding: utf-8 -*-
"""multithreading.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cm2ZbF4mdJ0vBZRrgp821jRtfLINs-33
"""

import time
import threading

def square(numbers):
  print("calculates sqyare of numbers")
  for n in numbers:
    time.sleep(0.2)
    print('Square : ', n*n)


def cube(numbers):
  print('Calculates cuber of numbers')
  for n in numbers:
    time.sleep(0.2)
    print('Cuber :' ,n*n*n)
  

arr = [2,3,8,9]

t = time.time()
t1 = threading.Thread(target = square,args=(arr,))
t2 = threading.Thread(target = cube,args=(arr,))

t1.start()
t2.start()

t1.join()
t2.join()

print('Done in :', time.time()-t)
print('Hah .. done with my work')