# -*- coding: utf-8 -*-
"""multiprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-AY7VNpws6ajET6YJIyqP-fRLDJFchd
"""

import time
import multiprocessing

square_result = []


def square(numbers):
  global square_result
  for n in numbers:
    print('square' + str(n*n))
    square_result.append(n*n)

  print("within a process : result " + str(square_result))


# def cube(numbers):
#   for n in numbers:
#     print('cube' + str(n*n*n))


arr = [2,3,8,9]

p1= multiprocessing.Process(target= square,args =(arr,))
# p2= multiprocessing.Process(target= cube,args =(arr,))

p1.start()
# p2.start()

p1.join()
print("aftera process : result " + str(square_result))

# p2.join()
 
print('ended')